# Generated by Django 5.1.5 on 2025-02-03 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("lists", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("action_type", models.CharField(max_length=50)),
                (
                    "list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="lists.list",
                    ),
                ),
                (
                    "member_creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.member",
                    ),
                ),
            ],
        ),
    ]
